;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	comment-dwim
	end-of-visual-line
	kill-visual-line
	next-buffer
	previous-buffer
	))

(setq mc/cmds-to-run-once
      '(
	drag-stuff-down
	drag-stuff-right
	duplicate-line
	eval-region
	helm-M-x
	lsp-ui-doc--handle-mouse-movement
	mouse-drag-vertical-line
	mouse-set-region
	))
