;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	beginning-of-visual-line
	end-of-visual-line
	next-buffer
	previous-buffer
	))

(setq mc/cmds-to-run-once
      '(
	drag-stuff-right
	duplicate-line
	eval-region
	))
