(require 'package)
(package-initialize)

(load-file "~/.emacsti/libs/execpathfromshell.el")
(load-file "~/.emacsti/libs/solarizedemacs.el")
(load-file "~/.emacsti/libs/powerline.el")
(load-file "~/.emacsti/libs/expandregion.el")
(load-file "~/.emacsti/libs/multiplecursors.el")
(load-file "~/.emacsti/libs/whichkey.el")
(load-file "~/.emacsti/libs/projectile.el")
(load-file "~/.emacsti/libs/company.el")
(load-file "~/.emacsti/libs/indent-guide.el")
(load-file "~/.emacsti/libs/yasnippet.el")
;; Starting block for Javascript support
(load-file "~/.emacsti/libs/js2-mode.el")
(load-file "~/.emacsti/libs/s.el")
(load-file "~/.emacsti/libs/dash.el")
(load-file "~/.emacsti/libs/js2-refactor.el")
(load-file "~/.emacsti/libs/xref-js2.el")
(load-file "~/.emacsti/libs/json-snatcher-1.0.0.el")
(load-file "~/.emacsti/libs/json-reformat-0.0.6.el")
(load-file "~/.emacsti/libs/json-mode.el")

;; (load-file "~/.emacsti/libs/postip.el")
;; (load-file "~/.emacsti/libs/quickpeek.el")
;; (load-file "~/.emacsti/libs/flycheck.el")
;; (load-file "~/.emacsti/libs/flycheckcolormodeline.el")
;; (load-file "~/.emacsti/libs/flycheckpostip.el")
;; (load-file "~/.emacsti/libs/flycheckstatusemoji.el")
;; (load-file "~/.emacsti/libs/flycheckinline.el")
;; (load-file "~/.emacsti/libs/aggressiveindent.el")

;; (load-file "~/.emacsti/libs/webmode.el")
;; (load-file "~/.emacsti/libs/typescript.el")
;; (load-file "~/.emacsti/libs/rjsxmode.el")
;; (load-file "~/.emacsti/libs/tide.el")
;; (load-file "~/.emacsti/libs/importjs.el")
