(require 'package)
(package-initialize)
(load-file "~/.emacsti/libs/bind-key.el")
(load-file "~/.emacsti/libs/use-package.el")
(load-file "~/.emacsti/libs/execpathfromshell.el")
(load-file "~/.emacsti/libs/solarizedemacs.el")
(load-file "~/.emacsti/libs/powerline.el")
(load-file "~/.emacsti/libs/expandregion.el")
(load-file "~/.emacsti/libs/multiplecursors.el")
(load-file "~/.emacsti/libs/whichkey.el")
(load-file "~/.emacsti/libs/projectile.el")
(load-file "~/.emacsti/libs/company.el")
(load-file "~/.emacsti/libs/ace-window.el")
;; (load-file "~/.emacsti/libs/postip.el")
;; (load-file "~/.emacsti/libs/quickpeek.el")
;; (load-file "~/.emacsti/libs/flycheck.el")
;; (load-file "~/.emacsti/libs/flycheckcolormodeline.el")
;; (load-file "~/.emacsti/libs/flycheckpostip.el")
;; (load-file "~/.emacsti/libs/flycheckstatusemoji.el")
;; (load-file "~/.emacsti/libs/flycheckinline.el")
;; (load-file "~/.emacsti/libs/aggressiveindent.el")
;; (load-file "~/.emacsti/libs/yasnippet.el")
;; (load-file "~/.emacsti/libs/webmode.el")
;; (load-file "~/.emacsti/libs/typescript.el")
;; (load-file "~/.emacsti/libs/rjsxmode.el")
;; (load-file "~/.emacsti/libs/tide.el")
;; (load-file "~/.emacsti/libs/importjs.el")
